# Generated by Django 5.2.1 on 2025-07-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nama',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='waktu_dikirim',
        ),
    ]
