# Generated by Django 5.2.1 on 2025-07-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_rename_nama_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='nama',
        ),
    ]
