# Generated by Django 5.2.4 on 2025-07-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='kodebarang',
            new_name='kdbrg',
        ),
        migrations.RenameField(
            model_name='barang',
            old_name='link_gambar',
            new_name='link_gbr',
        ),
    ]
