# Generated by Django 5.2.4 on 2025-07-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_rename_kodebarang_barang_kdbrg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/files/')),
                ('date_earned', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_earned'],
            },
        ),
    ]
