# Generated by Django 5.2.4 on 2025-07-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='github_url',
            new_name='github_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='live_url',
            new_name='live_demo_link',
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in showcase (lower numbers first)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in showcase carousel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Comma-separated list of technologies used', max_length=300),
        ),
    ]
