# Generated by Django 5.2.4 on 2025-07-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0009_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='Tentang Saya', max_length=200)),
                ('nama', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('jurusan', models.CharField(max_length=100)),
                ('universitas', models.CharField(max_length=100)),
                ('deskripsi_utama', models.TextField(help_text='Paragraf pembuka tentang diri Anda')),
                ('deskripsi_skill', models.TextField(help_text='Paragraf tentang skill yang sedang dikembangkan')),
                ('teknologi_kiri', models.TextField(help_text='Teknologi kolom kiri (pisahkan dengan koma)')),
                ('teknologi_kanan', models.TextField(help_text='Teknologi kolom kanan (pisahkan dengan koma)')),
                ('deskripsi_hobi', models.TextField(help_text='Paragraf tentang hobi dan aktivitas di luar kuliah')),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
